version: '3'

services:
  nginx:
    platform: linux/x86_64
    build:
      context: ./nginx
      args:
        USER_ID: $MAKE_ID
    ports:
      - 80:80
    volumes:
      - ./public:/appdata/www/public
    networks:
      - promotions-network

  promotions-api:
    container_name: promotions-api
    platform: linux/x86_64
    build:
      context: .
      args:
        USER_ID: $MAKE_ID
    volumes:
      - ./:/appdata/www
    depends_on:
      - nginx
      - promotions_database
    networks:
      - promotions-network

  promotions_database:
    container_name: promotions_database
    platform: linux/x86_64
    build:
      context: ./mysql
      args:
         USER_ID: $MAKE_ID
    ports:
      - 3350:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    networks:
      - promotions-network


networks:
  promotions-network:

